/*
Uptime, ver. 1.01
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STRLEN 128  //string length
#define HOSTNAME Vida

int result[3] = {0, 0, 0}; //days hours minutes
char resultnames[3][7] = {"day","hour","minute"}; //length shouldnt be > 6!

void begin(char *title){
  printf ("Content-type: text/html\n\n");
  printf ("<! -- Generated by Uptime 1.01 -->\n\n<html><head>\n<title>%s</title>\n</head>\n\n<body bgcolor=""black"">", title);
}

void sectotime(int seconds) {
  int i;
  const conversion[3] = {86400,3600,60};
  for (i=0;i<=2;i++) {
    result[i] = (seconds / conversion[i]);
    if (((seconds / conversion[i]) > 1) || ((seconds / conversion[i]) == 0)){
       strcat(resultnames[i], "s"); }
    seconds = (seconds % conversion[i]);
  }
}

int main(void) {
  int i;
  char *input = malloc(sizeof(char) * STRLEN + 1);
  float seconds;
  FILE *in;

  if ((in = fopen("/proc/uptime", "rt")) == 0){ printf("Can't open /proc/uptime!"); return 1;}

  begin("Uptime for host Vida");
  fscanf(in, "%s", input);
  sectotime(atoi(input));

  printf("\n\n<font color=red size=5>Vida Uptime: <font color=green>");
  for (i=0; i<=2; i++) {printf("%d %s ", result[i], resultnames[i]);}
  printf("\n</font>");

  fclose(in);
  return 0;
}
