
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060330
// Mon Apr 24 16:55:03 CEST 2006
//----------------------------------------------------

package sem2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 14;
  public static final int WITH = 36;
  public static final int CONST = 6;
  public static final int PACKED = 24;
  public static final int UINT = 58;
  public static final int GE = 43;
  public static final int ASSIGNMENT = 37;
  public static final int SLASH = 55;
  public static final int CASE = 5;
  public static final int NOTEQUAL = 50;
  public static final int UPARROW = 57;
  public static final int LPAREN = 47;
  public static final int REPEAT = 28;
  public static final int ARRAY = 3;
  public static final int RBRAC = 52;
  public static final int MINUS = 49;
  public static final int FOR = 13;
  public static final int STAR = 56;
  public static final int RPAREN = 53;
  public static final int SEMICOLON = 54;
  public static final int NOT = 21;
  public static final int AND = 2;
  public static final int LT = 48;
  public static final int RECORD = 27;
  public static final int TYPE = 32;
  public static final int NIL = 20;
  public static final int IN = 17;
  public static final int OR = 23;
  public static final int COMMA = 39;
  public static final int DOTDOT = 41;
  public static final int DIV = 7;
  public static final int BEGIN = 4;
  public static final int UNTIL = 33;
  public static final int PLUS = 51;
  public static final int IF = 16;
  public static final int DOT = 40;
  public static final int LE = 46;
  public static final int OF = 22;
  public static final int EOF = 0;
  public static final int EQUAL = 42;
  public static final int error = 1;
  public static final int PROGRAM = 26;
  public static final int MOD = 19;
  public static final int COLON = 38;
  public static final int ELSE = 10;
  public static final int TO = 31;
  public static final int FILE = 12;
  public static final int GOTO = 15;
  public static final int WHILE = 35;
  public static final int UNUMBER = 59;
  public static final int THEN = 30;
  public static final int END = 11;
  public static final int STRING = 60;
  public static final int LBRAC = 45;
  public static final int DOWNTO = 9;
  public static final int LABEL = 18;
  public static final int GT = 44;
  public static final int VAR = 34;
  public static final int PROCEDURE = 25;
  public static final int DO = 8;
  public static final int SET = 29;
  public static final int IDENTIFIER = 61;
}

